---
title: "Development of a reservoir morphology dataset to inform modeling greenhouse gas emissions from U.S. reservoirs."
author: "Jeffrey Hollister, Jake Beaulieu, Bridget Deemer, and Alex Hall"
format: docx
---

Understanding ecological processes in lentic systems, such as reservoirs, often requires the quantification of metrics of the waterbody's shape and size (i.e. morphology).  In support of ongoing efforts in the United States (U.S.) to better characterize greenhouse gas emissions from reservoirs, we have expanded past efforts (e.g. National Hydrography Dataset Plus), and are building a database of lake morphology for U.S. reservoirs. We use publicly available datasets to first build a database of U.S. reservoirs and then calculate the metrics for each using open source geospatial software (e.g. R).  Existing databases with relevant reservoir morphology metrics, such as LAGOS and the National Inventory of Dams, are also included.  The database includes estimates for 147 reservoirs measured as part of the Survey of Greenhouse Gas Emissions project led by the U.S. Environmental Protection Agency and efforts are underway to expand the number of included reservoirs.   We currently calculate 13 lake morphometry metrics including descriptors of lake shape (e.g. area, shoreline length), depth (e.g. mean depth, volume), and fetch.  These reservoirs had an average size of 516 hectares, predicted mean depth on average was 10 meters, and average maximum fetch was 2762 meters.  We present our procedures for developing the reservoir database and approaches for calculating each of the metrics.  The final database will be publicly available and will  support modeling of greenhouse gas emissions for the U.S. Inventory of Greenhouse Gas Emissions and Sinks.       